# Generated by Django 5.2.7 on 2025-10-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_reciever_message_title_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
