# Generated by Django 5.2.7 on 2025-11-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_message_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
