# Generated by Django 5.2.7 on 2025-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_list',
            name='subject_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
