# Generated by Django 5.2.7 on 2025-10-22 16:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_student')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, default='no description', null=True)),
                ('grade', models.IntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('form_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('session_price', models.IntegerField()),
                ('cv', models.FileField(upload_to='cv_tutor')),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('location_access', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, default='no description', null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_image_tutor')),
                ('education_data', models.JSONField(help_text='List of education levels and subjects.')),
                ('form_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
