# Generated by Django 5.2.7 on 2025-10-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '__first__'),
        ('requestapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_feedback', models.BooleanField(default=False)),
                ('req_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestapp.requesting_tutor')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile_student')),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile_tutor')),
            ],
        ),
    ]
