# Generated by Django 5.2.7 on 2025-10-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('profileapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requesting_tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10)),
                ('proposed_rate', models.IntegerField()),
                ('session_start_date', models.DateField()),
                ('session_end_date', models.DateField()),
                ('session_time_from', models.TimeField()),
                ('session_time_to', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('counter_time_from', models.CharField(blank=True, max_length=100, null=True)),
                ('counter_time_to', models.CharField(blank=True, max_length=100, null=True)),
                ('counter_start_date', models.DateField(blank=True, null=True)),
                ('counter_end_date', models.DateField(blank=True, null=True)),
                ('counter_proposed_rate', models.IntegerField(blank=True, null=True)),
                ('is_edit', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, default='no desc', null=True)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='profileapp.profile_student')),
                ('subject', models.ManyToManyField(to='categories.subjects_list')),
                ('tutor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve_requests', to='profileapp.profile_tutor')),
            ],
        ),
    ]
